export type Category = "leaves" | "flowers" | "herbs" | "trees" | "shrubs" | "climbers" | "medicinal"

export interface Species {
  id: string
  englishName: string
  botanicalName: string
  tamilName: string
  category: Category
  description: string
  fullDescription: string
  habitat: string
  uses: string[]
  characteristics: string[]
  image: string
}

export const speciesData: Species[] = [
  {
    id: "1",
    englishName: "Holy Basil",
    botanicalName: "Ocimum tenuiflorum",
    tamilName: "துளசி (Tulasi)",
    category: "herbs",
    description: "Sacred aromatic herb with powerful medicinal properties used in traditional medicine.",
    fullDescription: "Holy Basil, known as Tulasi in Tamil, is a sacred plant in Hindu tradition. It has been used for thousands of years in Ayurvedic medicine for its healing properties. The plant is revered for its ability to purify the air and is commonly grown in households across India.",
    habitat: "Native to the Indian subcontinent, thrives in warm, tropical climates with well-drained soil.",
    uses: ["Respiratory ailments", "Stress relief", "Immune booster", "Religious ceremonies", "Tea preparation"],
    characteristics: ["Aromatic leaves", "Purple or green stems", "Small purple flowers", "Height: 30-60 cm"],
    image: "https://th.bing.com/th/id/R.13eb1ffe7789e5be14689b72e58a10d6?rik=XXSbGOTeP2CMNg&riu=http%3a%2f%2fwww.ayurvalley.com%2fwp-content%2fuploads%2f2019%2f04%2fTulsi-or-holy-basil-Blog.jpg&ehk=aw433%2fprGVQuqsHvdWKpqhynyP0L7t%2fsVYJZMYHHtvU%3d&risl=&pid=ImgRaw&r=0"
  },
  {
    id: "2",
    englishName: "Indian shot",
    botanicalName: "Canna indica",
    tamilName: "Kal Vaalai (கல்வாழை)",
    category: "Plants",
    description: "Evergreen tree known as the 'village pharmacy' for its numerous medicinal uses.",
    fullDescription: "Canna indica, commonly known as Indian Shot, has a truly global footprint, spanning nearly every continent in tropical and subtropical zone. While its name might suggest otherwise, it is native to the Americas and has since naturalized pantropically through human trade and migration.",
    habitat: "A tall, erect perennial herb, typically reaching heights of 1–2.5 metres. Unlike the annual habit of Solanum nigrum, it persists for many years via its underground system",
    uses: ["Skin disorders", "Dental care", "Pest control", "Blood purification", "Diabetes management"],
    characteristics: ["Compound leaves", "White fragrant flowers", "Olive-like fruits", "Height: up to 20 meters"],
    image: "https://alchetron.com/cdn/canna-indica-a7a2fb0c-9b1d-4f6c-a8a5-6e11526ac85-resize-750.jpeg"
  },
  {
    id: "3",
    englishName: "Black nightshade",
    botanicalName: "Solanum nigrum",
    tamilName: "மணத்தக்காளி (Manathakkali)",
    category: "Plants",
    description: "Aquatic perennial flower symbolizing purity and enlightenment in Asian cultures.",
    fullDescription: "In India, Solanum nigrum is widely distributed throughout the country, from the plains to hilly regions up to about 2,000–2,500 m altitude.",
    habitat: "The plant grows in a wide range of habitats such as Roadsides, Waste Lands, Cultivated fields, Garderns, RiverBanks, Near Human Settlements",
    uses: ["Used to treat mouth ulcers, stomach ulcers, and gastric irritation."],
    image: "https://keys.lucidcentral.org/keys/v3/scotia/key/Plants%20and%20Fungi%20of%20south%20western%20NSW/Media/Images/Solanum_nigrum/Solanum_nigrum_Fagg_Boorowa-Crookwell_Rd.jpg"
  },
  {
    id: "4",
    englishName: "Yellow Bells, Yellow Trumpetbush, or Yellow Elder",
    botanicalName: "Tecoma Stans",
    tamilName: "நாக செண்பகம் (Naga Senbagam) ",
    category: "Plants",
    description: "A fast-growing ornamental flowering shrub/tree with bright yellow trumpet-shaped flowers, known for its drought tolerance",
    fullDescription: "Turmeric is one of the most important spices in Indian cuisine and traditional medicine. Its active compound, curcumin, has been extensively studied for its anti-inflammatory, antioxidant, and healing properties. It's an integral part of Indian culture and rituals.",
    habitat: "A fast-growing shrub or small tree, about 3–8 m tall, evergreen or semi-evergreen",
    uses: ["Diabetes", "Digestive Disorder", "Fever", "Skin Diseases"],
    characteristics: ["evergreen/semi-evergreen, attracts pollinators, low maintenance"],
    image: "https://www.bhg.com/thmb/fvD8i-pr2FGpxRfQXbutxejuqCg=/1280x0/filters:no_upscale():strip_icc()/yellow-bells-tecoma-stans-bloom-4f5bd9aa-0cc64de38ee749eb954be58ce6e97b4a.jpg"
  },
  {
    id: "5",
    englishName: "Jasmine",
    botanicalName: "Jasminum sambac",
    tamilName: "மல்லிகை (Mallikai)",
    category: "flowers",
    description: "Fragrant white flower used extensively in perfumery and religious ceremonies.",
    fullDescription: "Jasmine is beloved for its intensely sweet fragrance. In Tamil culture, women traditionally wear jasmine garlands in their hair. The flower is used in perfumes, teas, and religious offerings. It blooms primarily during summer evenings.",
    habitat: "Native to South and Southeast Asia, prefers warm climates with moderate humidity.",
    uses: ["Perfumery", "Hair adornment", "Aromatherapy", "Tea flavoring", "Religious offerings"],
    characteristics: ["Small white flowers", "Glossy green leaves", "Climbing or bushy habit", "Intense fragrance"],
    image: "https://tse4.mm.bing.net/th/id/OIP.Ox6GW2biWAEsSTJpLt36SgHaE7?rs=1&pid=ImgDetMain&o=7&rm=3"
  },
  {
    id: "6",
    englishName: "Banyan Tree",
    botanicalName: "Ficus benghalensis",
    tamilName: "ஆலமரம் (Aalamaram)",
    category: "trees",
    description: "Majestic fig tree with aerial roots, often considered sacred in Indian culture.",
    fullDescription: "The Banyan tree is known for its aerial prop roots that grow into thick woody trunks. It can spread over large areas and live for centuries. In Indian culture, it symbolizes eternal life and is often associated with temples and village gatherings.",
    habitat: "Native to Indian subcontinent, grows in tropical and subtropical climates.",
    uses: ["Shade provider", "Medicinal bark", "Religious significance", "Wood for crafts", "Wildlife habitat"],
    characteristics: ["Aerial roots", "Spreading canopy", "Leathery leaves", "Can cover several acres"],
    image: "https://th.bing.com/th/id/OIP.q7fd-rxYnNukynFM2yy8gQHaE8?o=7rm=3&rs=1&pid=ImgDetMain&o=7&rm=3"
  },
  {
    id: "7",
    englishName: "Aloe Vera",
    botanicalName: "Aloe barbadensis miller",
    tamilName: "கற்றாழை (Katrazhai)",
    category: "medicinal",
    description: "Succulent plant renowned for its gel with healing and moisturizing properties.",
    fullDescription: "Aloe Vera has been used for medicinal purposes for thousands of years. The clear gel inside its leaves contains vitamins, minerals, and amino acids that promote healing. It's widely used in skincare, haircare, and treating burns and wounds.",
    habitat: "Native to Arabian Peninsula, now cultivated worldwide in arid and semi-arid regions.",
    uses: ["Skin healing", "Hair care", "Digestive health", "Sunburn relief", "Cosmetics"],
    characteristics: ["Thick fleshy leaves", "Serrated edges", "Yellow tubular flowers", "Height: 60-100 cm"],
    image: "https://tse3.mm.bing.net/th/id/OIP._EWRIZG4G8zy69ete5xB0AHaE8?rs=1&pid=ImgDetMain&o=7&rm=3"
  },
  {
    id: "8",
    englishName: "Hibiscus",
    botanicalName: "Hibiscus rosa-sinensis",
    tamilName: "செம்பருத்தி (Sembaruthi)",
    category: "flowers",
    description: "Vibrant tropical flower used for hair care and traditional medicine.",
    fullDescription: "Hibiscus is known for its large, colorful trumpet-shaped flowers. In Tamil Nadu, the red hibiscus is commonly used for hair care and as offerings to Hindu deities. The flower has cooling properties and is used to make refreshing drinks.",
    habitat: "Tropical and subtropical regions, requires full sun and regular watering.",
    uses: ["Hair growth", "Natural dye", "Herbal tea", "Religious offerings", "Ornamental"],
    characteristics: ["Large trumpet flowers", "Glossy dark leaves", "Various colors", "Height: 2-5 meters"],
    image: "https://tse3.mm.bing.net/th/id/OIP.OootZJbhwcXhptAn8lnIWgHaFj?w=1024&h=768&rs=1&pid=ImgDetMain&o=7&rm=3"
  },
  {
    id: "9",
    englishName: "Curry Leaf",
    botanicalName: "Murraya koenigii",
    tamilName: "கறிவேப்பிலை (Kariveppilai)",
    category: "leaves",
    description: "Aromatic leaves essential in South Indian cuisine with numerous health benefits.",
    fullDescription: "Curry leaves are indispensable in South Indian cooking, providing a distinctive aroma and flavor. Beyond culinary use, they have numerous health benefits including improving digestion, promoting hair health, and managing diabetes.",
    habitat: "Native to India and Sri Lanka, grows well in tropical to subtropical climates.",
    uses: ["Cooking", "Hair health", "Diabetes management", "Digestive aid", "Eye health"],
    characteristics: ["Pinnate leaves", "Small white flowers", "Black berries", "Height: 4-6 meters"],
    image: "https://images.unsplash.com/photo-1638500568943-3b899d86e7d3?w=400&h=300&fit=crop"
  },
  {
    id: "10",
    englishName: "Moringa",
    botanicalName: "Moringa oleifera",
    tamilName: "முருங்கை (Murungai)",
    category: "trees",
    description: "Nutrient-rich 'miracle tree' with edible leaves, pods, and numerous health benefits.",
    fullDescription: "Moringa is called the 'miracle tree' because almost every part is edible and nutritious. The leaves are packed with vitamins and minerals. Drumsticks (seed pods) are a popular vegetable in South Indian cuisine, especially in sambar.",
    habitat: "Native to India, thrives in tropical and subtropical dry climates.",
    uses: ["Nutrition supplement", "Water purification", "Cooking", "Traditional medicine", "Animal feed"],
    characteristics: ["Feathery leaves", "White fragrant flowers", "Long seed pods", "Height: up to 12 meters"],
    image: "https://images.unsplash.com/photo-1605637297601-3ee67a0cdc3d?w=400&h=300&fit=crop"
  },
  {
    id: "11",
    englishName: "Marigold",
    botanicalName: "Tagetes erecta",
    tamilName: "செண்டுமல்லி (Sendumalli)",
    category: "flowers",
    description: "Bright golden flowers widely used in festivals, garlands, and natural dyes.",
    fullDescription: "Marigolds are ubiquitous in Indian festivals and ceremonies. Their bright orange and yellow blooms are used to make garlands, decorate temples, and in traditional medicine. The flowers also have natural pest-repelling properties.",
    habitat: "Native to Americas, widely cultivated in India in various climates.",
    uses: ["Garlands", "Temple decorations", "Natural dye", "Pest repellent", "Eye health"],
    characteristics: ["Pompom-like flowers", "Pinnate leaves", "Strong scent", "Height: 30-90 cm"],
    image: "https://images.unsplash.com/photo-1597848212624-a19eb35e2651?w=400&h=300&fit=crop"
  },
  {
    id: "12",
    englishName: "Ashwagandha",
    botanicalName: "Withania somnifera",
    tamilName: "அமுக்கிரா கிழங்கு (Amukkira Kilangu)",
    category: "medicinal",
    description: "Ancient medicinal herb known for its adaptogenic and rejuvenating properties.",
    fullDescription: "Ashwagandha is one of the most important herbs in Ayurveda. Known as Indian Ginseng, it helps the body adapt to stress, boosts energy, and improves concentration. The root has been used for over 3,000 years to relieve stress and increase vitality.",
    habitat: "Native to India and North Africa, grows in dry regions and poor soil.",
    uses: ["Stress relief", "Energy boost", "Memory enhancement", "Immune support", "Sleep aid"],
    characteristics: ["Yellow-green flowers", "Red berries", "Oval leaves", "Height: 35-75 cm"],
    image: "https://images.unsplash.com/photo-1611241893603-3c359704e0ee?w=400&h=300&fit=crop"
  },
  {
    id: "13",
    englishName: "Betel Leaf",
    botanicalName: "Piper betle",
    tamilName: "வெற்றிலை (Vetrilai)",
    category: "leaves",
    description: "Heart-shaped aromatic leaf used in traditional practices and digestive aid.",
    fullDescription: "Betel leaf holds great cultural significance in India. It's traditionally offered to guests and used in religious ceremonies. Chewing betel leaf aids digestion and freshens breath. The leaf has antibacterial and anti-inflammatory properties.",
    habitat: "Native to Southeast Asia, grows as a climbing vine in tropical humid conditions.",
    uses: ["Digestive aid", "Mouth freshener", "Religious ceremonies", "Traditional medicine", "Cultural rituals"],
    characteristics: ["Heart-shaped leaves", "Climbing vine", "Glossy surface", "Peppery taste"],
    image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=400&h=300&fit=crop"
  },
  {
    id: "14",
    englishName: "Tamarind",
    botanicalName: "Tamarindus indica",
    tamilName: "புளி (Puli)",
    category: "trees",
    description: "Tropical tree with tangy fruit pods essential in South Indian cuisine.",
    fullDescription: "Tamarind is integral to South Indian cooking, providing the signature sour taste to sambar, rasam, and chutneys. The tree is long-lived and provides dense shade. Every part of the tree has uses, from the fruit pulp to the wood.",
    habitat: "Native to tropical Africa, extensively cultivated in India.",
    uses: ["Cooking", "Traditional medicine", "Metal polish", "Wood for furniture", "Beverages"],
    characteristics: ["Feathery compound leaves", "Brown seed pods", "Dense canopy", "Height: up to 25 meters"],
    image: "https://images.unsplash.com/photo-1594631252845-29fc4cc8cde9?w=400&h=300&fit=crop"
  },
  {
    id: "15",
    englishName: "Indian Gooseberry",
    botanicalName: "Phyllanthus emblica",
    tamilName: "நெல்லிக்காய் (Nellikai)",
    category: "medicinal",
    description: "Vitamin C-rich fruit known as Amla, used extensively in Ayurvedic medicine.",
    fullDescription: "Amla or Indian Gooseberry is one of the richest sources of Vitamin C. It's a key ingredient in Chyawanprash and many Ayurvedic formulations. The fruit promotes immunity, improves digestion, and is excellent for hair and skin health.",
    habitat: "Native to India, grows in tropical and subtropical regions.",
    uses: ["Immunity booster", "Hair care", "Digestive health", "Pickles", "Ayurvedic medicine"],
    characteristics: ["Small green fruits", "Feathery leaves", "Grey bark", "Height: 8-18 meters"],
    image: "https://images.unsplash.com/photo-1609428927607-1de0d9a97cd0?w=400&h=300&fit=crop"
  },
  {
    id: "16",
    englishName: "Mango",
    botanicalName: "Mangifera indica",
    tamilName: "மாம்பழம் (Maampazham)",
    category: "trees",
    description: "King of fruits with sweet, juicy flesh beloved throughout India and the world.",
    fullDescription: "Mango is the national fruit of India and has been cultivated for over 4,000 years. India is the largest producer of mangoes in the world. The fruit is not only delicious but also rich in vitamins A and C. Raw mangoes are used in pickles and chutneys.",
    habitat: "Native to South Asia, grows in tropical and subtropical climates.",
    uses: ["Fresh fruit", "Pickles", "Chutneys", "Dried fruit", "Juices and smoothies"],
    characteristics: ["Large evergreen tree", "Fragrant flowers", "Drupe fruit", "Height: up to 40 meters"],
    image: "https://images.unsplash.com/photo-1553279768-865429fa0078?w=400&h=300&fit=crop"
  },
  {
    id: "17",
    englishName: "Mint",
    botanicalName: "Mentha arvensis",
    tamilName: "புதினா (Pudhina)",
    category: "herbs",
    description: "Refreshing aromatic herb used in cooking, beverages, and traditional medicine.",
    fullDescription: "Mint is a versatile herb known for its cooling, refreshing taste. It's used in chutneys, drinks, and as a garnish. Mint aids digestion, relieves headaches, and has antibacterial properties. It's easy to grow and spreads rapidly.",
    habitat: "Native to Europe and Asia, grows well in moist, partially shaded conditions.",
    uses: ["Cooking", "Beverages", "Digestive aid", "Aromatherapy", "Oral care"],
    characteristics: ["Square stems", "Opposite leaves", "Purple-white flowers", "Height: 10-60 cm"],
    image: "https://images.unsplash.com/photo-1628556270448-4d4e4148e1b1?w=400&h=300&fit=crop"
  },
  {
    id: "18",
    englishName: "Coriander",
    botanicalName: "Coriandrum sativum",
    tamilName: "கொத்தமல்லி (Kothamalli)",
    category: "herbs",
    description: "Aromatic herb with edible leaves and seeds, essential in Indian cooking.",
    fullDescription: "Coriander is indispensable in Indian cuisine. Fresh leaves are used as garnish and in chutneys, while dried seeds are a key spice in many dishes. The plant has digestive and anti-inflammatory properties. Both leaves and seeds have distinct flavors.",
    habitat: "Native to Mediterranean and Middle East, cultivated worldwide.",
    uses: ["Cooking", "Digestive aid", "Spice", "Garnish", "Traditional medicine"],
    characteristics: ["Delicate leaves", "White-pink flowers", "Round seeds", "Height: 50-100 cm"],
    image: "https://images.unsplash.com/photo-1595855759920-86582396756a?w=400&h=300&fit=crop"
  },
  {
    id: "19",
    englishName: "Rose",
    botanicalName: "Rosa indica",
    tamilName: "ரோஜா (Roja)",
    category: "flowers",
    description: "Classic flower symbolizing love, used in perfumes, food, and medicine.",
    fullDescription: "Roses have been cultivated in India for centuries. Rose water and rose oil are prized in perfumery and cooking. Rose petals are used in gulkand, a sweet preserve with cooling properties. The flower has anti-inflammatory and mood-enhancing benefits.",
    habitat: "Native to Asia, cultivated worldwide in temperate and subtropical climates.",
    uses: ["Perfumery", "Gulkand", "Rose water", "Ornamental", "Skincare"],
    characteristics: ["Thorny stems", "Fragrant flowers", "Various colors", "Height: 30 cm to 7 meters"],
    image: "https://images.unsplash.com/photo-1559563362-c667ba5f5480?w=400&h=300&fit=crop"
  },
  {
    id: "20",
    englishName: "Papaya",
    botanicalName: "Carica papaya",
    tamilName: "பப்பாளி (Pappali)",
    category: "trees",
    description: "Tropical fruit tree with digestive enzyme papain and numerous health benefits.",
    fullDescription: "Papaya is a fast-growing tropical fruit tree. The fruit contains papain, a digestive enzyme. Ripe papaya is sweet and nutritious, while raw papaya is used in salads and cooking. The leaves are also used in traditional medicine.",
    habitat: "Native to Central America, now grown throughout tropics including India.",
    uses: ["Fresh fruit", "Digestive aid", "Meat tenderizer", "Skincare", "Traditional medicine"],
    characteristics: ["Hollow trunk", "Large lobed leaves", "Orange flesh", "Height: 5-10 meters"],
    image: "https://images.unsplash.com/photo-1517282009859-f000ec3b26fe?w=400&h=300&fit=crop"
  },
  {
    id: "21",
    englishName: "Bougainvillea",
    botanicalName: "Bougainvillea spectabilis",
    tamilName: "காகிதப்பூ (Kagidhapoo)",
    category: "climbers",
    description: "Vibrant ornamental vine with colorful bracts that adorn gardens and walls.",
    fullDescription: "Bougainvillea is a spectacular ornamental plant known for its vibrant colored bracts (often mistaken for petals). It's drought-tolerant and blooms profusely. The plant is widely used for landscaping, covering walls, and as hedges.",
    habitat: "Native to South America, thrives in hot, dry climates.",
    uses: ["Ornamental", "Landscaping", "Traditional medicine", "Natural fence", "Air purification"],
    characteristics: ["Thorny woody vine", "Colorful bracts", "Small white flowers", "Can grow over 12 meters"],
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=300&fit=crop"
  },
  {
    id: "22",
    englishName: "Sandalwood",
    botanicalName: "Santalum album",
    tamilName: "சந்தனம் (Chandanam)",
    category: "trees",
    description: "Precious fragrant wood used in perfumes, religious rituals, and traditional medicine.",
    fullDescription: "Sandalwood is one of the most valuable trees in the world, prized for its fragrant heartwood. The oil extracted is used in perfumes, cosmetics, and medicine. Sandalwood paste is applied during religious ceremonies and is known for its cooling properties.",
    habitat: "Native to Southern India, grows in dry deciduous forests.",
    uses: ["Perfumery", "Religious rituals", "Skincare", "Aromatherapy", "Carving"],
    characteristics: ["Evergreen tree", "Fragrant heartwood", "Small flowers", "Height: 4-9 meters"],
    image: "https://images.unsplash.com/photo-1599497436459-a5a2dedf7329?w=400&h=300&fit=crop"
  },
  {
    id: "23",
    englishName: "Brahmi",
    botanicalName: "Bacopa monnieri",
    tamilName: "பிரம்மி (Brahmi)",
    category: "medicinal",
    description: "Memory-enhancing herb used in Ayurveda for cognitive function and stress relief.",
    fullDescription: "Brahmi is a renowned brain tonic in Ayurveda. It enhances memory, concentration, and learning ability. The herb grows in wetlands and is named after Lord Brahma, the creator god. It's also known for reducing anxiety and stress.",
    habitat: "Native to wetlands of India, grows in marshy areas and along riverbanks.",
    uses: ["Memory enhancement", "Stress relief", "Hair care", "Wound healing", "Epilepsy treatment"],
    characteristics: ["Small succulent leaves", "White-purple flowers", "Creeping stems", "Height: 6 inches"],
    image: "https://images.unsplash.com/photo-1509223197845-458d87a3f2a5?w=400&h=300&fit=crop"
  },
  {
    id: "24",
    englishName: "Pomegranate",
    botanicalName: "Punica granatum",
    tamilName: "மாதுளை (Mathulai)",
    category: "shrubs",
    description: "Ancient fruit with ruby-red arils packed with antioxidants and health benefits.",
    fullDescription: "Pomegranate has been cultivated in India for millennia. The ruby-red arils are rich in antioxidants, particularly punicalagins. The fruit is mentioned in ancient texts and is associated with fertility and abundance. The rind and flowers also have medicinal uses.",
    habitat: "Native to Iran to Northern India, grows in semi-arid conditions.",
    uses: ["Fresh fruit", "Juice", "Culinary garnish", "Traditional medicine", "Natural dye"],
    characteristics: ["Deciduous shrub", "Red-orange flowers", "Leathery rind", "Height: 5-10 meters"],
    image: "https://images.unsplash.com/photo-1541344999736-83eca272f6fc?w=400&h=300&fit=crop"
  },
  {
    id: "25",
    englishName: "Tulip Tree",
    botanicalName: "Spathodea campanulata",
    tamilName: "பட்டாசு பூ மரம் (Pattasu Poo Maram)",
    category: "trees",
    description: "Stunning ornamental tree with flame-colored tulip-shaped flowers.",
    fullDescription: "The African Tulip Tree is known for its spectacular display of flame-colored flowers. Native to Africa, it has been widely planted in India as an ornamental tree. The flowers produce abundant nectar, attracting birds and insects.",
    habitat: "Native to tropical Africa, grows well in humid tropical climates.",
    uses: ["Ornamental", "Avenue tree", "Traditional medicine", "Firewood", "Timber"],
    characteristics: ["Large compound leaves", "Tulip-shaped flowers", "Boat-shaped pods", "Height: 7-25 meters"],
    image: "https://images.unsplash.com/photo-1527061011665-3652c757a4d4?w=400&h=300&fit=crop"
  },
  {
    id: "26",
    englishName: "Night Jasmine",
    botanicalName: "Nyctanthes arbor-tristis",
    tamilName: "பவழமல்லி (Pavalamalli)",
    category: "flowers",
    description: "Fragrant night-blooming flower that drops at dawn, used in worship and medicine.",
    fullDescription: "Night Jasmine blooms after sunset and drops its flowers at dawn. The fragrant white and orange flowers are used in religious offerings. The leaves, flowers, and seeds have medicinal properties, used to treat fever, arthritis, and skin conditions.",
    habitat: "Native to South Asia, grows in tropical and subtropical regions.",
    uses: ["Religious offerings", "Fever treatment", "Natural dye", "Perfumery", "Traditional medicine"],
    characteristics: ["Night blooming", "White-orange flowers", "Fragrant", "Height: 3-10 meters"],
    image: "https://images.unsplash.com/photo-1490750967868-88aa4486c946?w=400&h=300&fit=crop"
  },
  {
    id: "27",
    englishName: "Fenugreek",
    botanicalName: "Trigonella foenum-graecum",
    tamilName: "வெந்தயம் (Vendhayam)",
    category: "herbs",
    description: "Versatile herb with seeds and leaves used in cooking and traditional medicine.",
    fullDescription: "Fenugreek is valued for both its aromatic leaves and bitter seeds. The seeds are a common spice in Indian cuisine, while fresh leaves (methi) are cooked as a vegetable. It helps control blood sugar and promotes lactation in nursing mothers.",
    habitat: "Native to Mediterranean region, widely cultivated in India.",
    uses: ["Cooking", "Blood sugar control", "Hair care", "Lactation support", "Digestive aid"],
    characteristics: ["Trifoliate leaves", "White flowers", "Long seed pods", "Height: 30-60 cm"],
    image: "https://images.unsplash.com/photo-1615485291926-559b9b350c54?w=400&h=300&fit=crop"
  },
  {
    id: "28",
    englishName: "Lemongrass",
    botanicalName: "Cymbopogon citratus",
    tamilName: "எலுமிச்சை புல் (Elumichai Pul)",
    category: "herbs",
    description: "Aromatic grass with citrus flavor used in cooking, teas, and aromatherapy.",
    fullDescription: "Lemongrass is a tropical grass with a distinct lemony aroma and flavor. It's used in Asian cuisine, herbal teas, and essential oil production. The oil has antiseptic, antibacterial, and insect-repelling properties.",
    habitat: "Native to South Asia, grows in tropical and subtropical regions.",
    uses: ["Cooking", "Herbal tea", "Aromatherapy", "Insect repellent", "Traditional medicine"],
    characteristics: ["Long blade-like leaves", "Lemony scent", "Clumping grass", "Height: 1-1.5 meters"],
    image: "https://images.unsplash.com/photo-1518164147695-36c13dd568f5?w=400&h=300&fit=crop"
  },
  {
    id: "29",
    englishName: "Indian Pennywort",
    botanicalName: "Centella asiatica",
    tamilName: "வல்லாரை (Vallarai)",
    category: "medicinal",
    description: "Memory-boosting herb also known as Gotu Kola, used for cognitive enhancement.",
    fullDescription: "Vallarai or Gotu Kola is a small creeping herb known for its brain-boosting properties. In Tamil tradition, it's fed to children to improve memory and intelligence. The herb also promotes wound healing and has anti-anxiety effects.",
    habitat: "Native to wetlands of Asia, grows in damp, shady areas.",
    uses: ["Memory enhancement", "Wound healing", "Skin care", "Anxiety relief", "Longevity tonic"],
    characteristics: ["Kidney-shaped leaves", "Pink-white flowers", "Creeping habit", "Height: 5-15 cm"],
    image: "https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=400&h=300&fit=crop"
  },
  {
    id: "30",
    englishName: "Jackfruit",
    botanicalName: "Artocarpus heterophyllus",
    tamilName: "பலாப்பழம் (Palapazham)",
    category: "trees",
    description: "World's largest tree fruit with sweet flesh and nutritious seeds.",
    fullDescription: "Jackfruit is the largest tree-borne fruit in the world, growing up to 35 kg. The sweet, fibrous flesh is eaten fresh or cooked. Young jackfruit is used as a meat substitute. The seeds are edible when roasted or boiled.",
    habitat: "Native to South and Southeast Asia, grows in tropical lowlands.",
    uses: ["Fresh fruit", "Vegetable dishes", "Meat alternative", "Roasted seeds", "Wood for furniture"],
    characteristics: ["Large compound fruit", "Spiky exterior", "Yellow flesh", "Height: up to 25 meters"],
    image: "https://images.unsplash.com/photo-1595266668901-cced3d93b040?w=400&h=300&fit=crop"
  },
  {
    id: "31",
    englishName: "Ginger",
    botanicalName: "Zingiber officinale",
    tamilName: "இஞ்சி (Inji)",
    category: "herbs",
    description: "Pungent rhizome essential in cooking and traditional medicine worldwide.",
    fullDescription: "Ginger is one of the most widely used spices in the world. Its pungent, warming flavor is essential in Indian cuisine. Medicinally, it aids digestion, relieves nausea, reduces inflammation, and fights respiratory infections.",
    habitat: "Native to Southeast Asia, cultivated in tropical regions worldwide.",
    uses: ["Cooking", "Digestive aid", "Nausea relief", "Cold remedy", "Anti-inflammatory"],
    characteristics: ["Rhizomatous root", "Lance-shaped leaves", "Yellow-green flowers", "Height: 60-90 cm"],
    image: "https://images.unsplash.com/photo-1573521193826-58c7dc2e13e3?w=400&h=300&fit=crop"
  },
  {
    id: "32",
    englishName: "Coconut Palm",
    botanicalName: "Cocos nucifera",
    tamilName: "தென்னை மரம் (Thennai Maram)",
    category: "trees",
    description: "Versatile 'tree of life' providing food, water, oil, and countless products.",
    fullDescription: "The coconut palm is called the 'tree of life' because every part is useful. Coconut water, milk, oil, and flesh are dietary staples. Coir from the husk is used for ropes and mats. The palm is central to coastal economies and cuisine.",
    habitat: "Native to tropical coastlines, grows in sandy, saline soils.",
    uses: ["Coconut water", "Cooking oil", "Coconut milk", "Coir products", "Palm sugar"],
    characteristics: ["Tall single trunk", "Feathery fronds", "Large drupes", "Height: up to 30 meters"],
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=400&h=300&fit=crop"
  },
  {
    id: "33",
    englishName: "Money Plant",
    botanicalName: "Epipremnum aureum",
    tamilName: "பணம் செடி (Panam Chedi)",
    category: "climbers",
    description: "Popular indoor plant believed to bring prosperity and purify air.",
    fullDescription: "Money Plant is one of the most popular houseplants in India. According to Vastu and Feng Shui, it brings good luck and financial prosperity. It's an excellent air purifier and can grow in water or soil with minimal care.",
    habitat: "Native to Southeast Asia, grows as indoor or outdoor plant in tropical climates.",
    uses: ["Air purification", "Ornamental", "Feng Shui", "Indoor decoration", "Ground cover"],
    characteristics: ["Heart-shaped leaves", "Climbing vine", "Yellow variegation", "Can grow several meters"],
    image: "https://images.unsplash.com/photo-1620127807580-990c3ecebd14?w=400&h=300&fit=crop"
  },
  {
    id: "34",
    englishName: "Vetiver",
    botanicalName: "Chrysopogon zizanioides",
    tamilName: "வெட்டிவேர் (Vettiver)",
    category: "herbs",
    description: "Aromatic grass with fragrant roots used in perfumery and soil conservation.",
    fullDescription: "Vetiver is known for its aromatic roots that are used in perfumery and traditional cooling methods. Vetiver curtains (khus curtains) are used in summer for natural air conditioning. The deep root system prevents soil erosion.",
    habitat: "Native to India, grows in tropical and subtropical regions.",
    uses: ["Perfumery", "Natural cooling", "Soil conservation", "Aromatherapy", "Traditional medicine"],
    characteristics: ["Tall clumping grass", "Fragrant roots", "No runners", "Height: 1.5-2 meters"],
    image: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=400&h=300&fit=crop"
  },
  {
    id: "35",
    englishName: "Bamboo",
    botanicalName: "Bambusa bambos",
    tamilName: "மூங்கில் (Moongil)",
    category: "trees",
    description: "Fast-growing giant grass with remarkable strength and countless applications.",
    fullDescription: "Bamboo is the fastest-growing plant on Earth and one of the most versatile. In India, it's used for construction, furniture, food, and crafts. Bamboo shoots are edible, and the plant plays a crucial role in preventing soil erosion.",
    habitat: "Native to tropical and subtropical regions, grows in various soil types.",
    uses: ["Construction", "Furniture", "Food", "Paper making", "Musical instruments"],
    characteristics: ["Hollow stems", "Rapid growth", "Extensive rhizomes", "Height: up to 30 meters"],
    image: "https://images.unsplash.com/photo-1518495973542-4542c06a5843?w=400&h=300&fit=crop"
  },
  {
    id: "36",
    englishName: "Shatavari",
    botanicalName: "Asparagus racemosus",
    tamilName: "தண்ணீர்விட்டான் கிழங்கு (Thanneervittan Kilangu)",
    category: "medicinal",
    description: "Queen of herbs in Ayurveda, known for supporting female reproductive health.",
    fullDescription: "Shatavari means 'she who possesses a hundred husbands,' referring to its rejuvenating effects. It's the primary herb for women's health in Ayurveda, supporting fertility, lactation, and menopause. It's also an excellent adaptogen for both sexes.",
    habitat: "Native to India and the Himalayas, grows in tropical forests.",
    uses: ["Women's health", "Lactation support", "Digestive health", "Immune support", "Adaptogen"],
    characteristics: ["Climbing plant", "Needle-like leaves", "White fragrant flowers", "Tuberous roots"],
    image: "https://images.unsplash.com/photo-1590069261209-f8e9b8642343?w=400&h=300&fit=crop"
  },
  {
    id: "37",
    englishName: "Banana Plant",
    botanicalName: "Musa paradisiaca",
    tamilName: "வாழை மரம் (Vaazhai Maram)",
    category: "herbs",
    description: "Versatile plant with edible fruit, flower, and leaves used in cooking and ceremonies.",
    fullDescription: "The banana plant is technically a giant herb, not a tree. Every part is useful - fruit for eating, leaves for serving food and wrapping, flower (vazhaipoo) as vegetable, and stem as fiber. It's considered auspicious in Hindu culture.",
    habitat: "Native to Southeast Asia, widely cultivated in tropical regions.",
    uses: ["Fruit consumption", "Leaf plates", "Flower vegetable", "Stem fiber", "Religious ceremonies"],
    characteristics: ["Large pseudo-stem", "Giant leaves", "Hanging inflorescence", "Height: 2-9 meters"],
    image: "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=400&h=300&fit=crop"
  },
  {
    id: "38",
    englishName: "Custard Apple",
    botanicalName: "Annona squamosa",
    tamilName: "சீதாப்பழம் (Seethapazham)",
    category: "trees",
    description: "Sweet creamy fruit with custard-like texture beloved for its unique flavor.",
    fullDescription: "Custard Apple, called Sitaphal in Hindi and Seethapazham in Tamil, has a creamy, sweet flesh with a custard-like texture. The fruit is rich in vitamins and minerals. The seeds, bark, and leaves have medicinal properties but should be used carefully.",
    habitat: "Native to tropical Americas, widely cultivated in India.",
    uses: ["Fresh fruit", "Ice cream flavoring", "Traditional medicine", "Insecticide from seeds"],
    characteristics: ["Small deciduous tree", "Heart-shaped fruits", "Scaly green skin", "Height: 3-8 meters"],
    image: "https://images.unsplash.com/photo-1601493700631-2b16ec4b4716?w=400&h=300&fit=crop"
  },
  {
    id: "39",
    englishName: "Drumstick Leaf",
    botanicalName: "Moringa oleifera",
    tamilName: "முருங்கை இலை (Murungai Ilai)",
    category: "leaves",
    description: "Nutrient-dense leaves packed with vitamins, minerals, and protein.",
    fullDescription: "Moringa leaves are one of the most nutrient-dense foods on the planet. They contain all essential amino acids, making them a complete protein source. The leaves are used in curries, soups, and dried into powder as a supplement.",
    habitat: "Native to India, thrives in tropical and subtropical dry climates.",
    uses: ["Nutritious vegetable", "Protein supplement", "Traditional medicine", "Animal feed", "Water purification"],
    characteristics: ["Small round leaflets", "Compound leaves", "Bitter taste", "Highly nutritious"],
    image: "https://images.unsplash.com/photo-1597700431425-d87ad8d8b2c7?w=400&h=300&fit=crop"
  },
  {
    id: "40",
    englishName: "Indian Mulberry",
    botanicalName: "Morinda citrifolia",
    tamilName: "நுணா (Nuna)",
    category: "medicinal",
    description: "Medicinal plant with fruit used in traditional healing practices worldwide.",
    fullDescription: "Known as Noni, this plant has been used in traditional medicine for over 2,000 years. The fruit, leaves, and roots have numerous health benefits. Despite its pungent smell, noni juice is popular as a health tonic for immunity and energy.",
    habitat: "Native to Southeast Asia and Australia, grows in coastal regions.",
    uses: ["Health tonic", "Immune support", "Pain relief", "Skin healing", "Traditional medicine"],
    characteristics: ["Glossy leaves", "White tubular flowers", "Lumpy green fruit", "Height: 3-10 meters"],
    image: "https://images.unsplash.com/photo-1502217625004-89c03571bcca?w=400&h=300&fit=crop"
  },
  {
    id: "41",
    englishName: "Passion Flower",
    botanicalName: "Passiflora incarnata",
    tamilName: "சிறுபூளை (Sirupulai)",
    category: "climbers",
    description: "Exotic climbing vine with intricate flowers and calming medicinal properties.",
    fullDescription: "Passion Flower has one of the most intricate and beautiful flowers in the plant kingdom. Beyond its ornamental value, it has powerful calming properties and is used to treat anxiety and insomnia. The fruit is also edible and delicious.",
    habitat: "Native to Americas, grows in tropical and subtropical regions.",
    uses: ["Anxiety relief", "Sleep aid", "Ornamental", "Edible fruit", "Herbal tea"],
    characteristics: ["Climbing tendrils", "Complex flowers", "Round fruit", "Fast growing"],
    image: "https://images.unsplash.com/photo-1597586124394-fbd6ef244026?w=400&h=300&fit=crop"
  },
  {
    id: "42",
    englishName: "Guava",
    botanicalName: "Psidium guajava",
    tamilName: "கொய்யா (Koiya)",
    category: "trees",
    description: "Vitamin C-rich tropical fruit with fragrant flesh and edible seeds.",
    fullDescription: "Guava is one of the richest sources of Vitamin C, containing more than oranges. The fruit can be eaten fresh, juiced, or made into jelly. Guava leaves have medicinal properties and are used to treat diarrhea and lower blood sugar.",
    habitat: "Native to Central America, widely cultivated in India.",
    uses: ["Fresh fruit", "Juice", "Jelly", "Traditional medicine", "Leaf extract"],
    characteristics: ["Green to yellow fruit", "Pink or white flesh", "Fragrant", "Height: 3-10 meters"],
    image: "https://images.unsplash.com/photo-1536511132770-e5058c7e8c46?w=400&h=300&fit=crop"
  },
  {
    id: "43",
    englishName: "Curry Plant",
    botanicalName: "Helichrysum italicum",
    tamilName: "கறி செடி (Kari Chedi)",
    category: "shrubs",
    description: "Silver-leaved aromatic shrub with a curry-like fragrance used in cooking.",
    fullDescription: "Despite its name, the Curry Plant is not used in traditional Indian curry but has a similar aroma. This silver-leaved Mediterranean shrub is used in cooking, particularly in Italian and French cuisine. The essential oil has anti-inflammatory properties.",
    habitat: "Native to Mediterranean region, grows in dry, sunny conditions.",
    uses: ["Culinary herb", "Essential oil", "Ornamental", "Dried arrangements", "Traditional medicine"],
    characteristics: ["Silver-grey leaves", "Yellow flowers", "Strong curry scent", "Height: 40-60 cm"],
    image: "https://images.unsplash.com/photo-1518164147695-36c13dd568f5?w=400&h=300&fit=crop"
  },
  {
    id: "44",
    englishName: "Bitter Gourd",
    botanicalName: "Momordica charantia",
    tamilName: "பாகற்காய் (Pagarkai)",
    category: "climbers",
    description: "Bitter vegetable known for its blood sugar-lowering properties.",
    fullDescription: "Bitter Gourd is famous for its extremely bitter taste and remarkable health benefits. It's particularly effective in managing diabetes and is rich in vitamins and antioxidants. Despite the bitter taste, it's a beloved vegetable in Indian cuisine.",
    habitat: "Native to India and surrounding regions, grows in tropical climates.",
    uses: ["Diabetes management", "Blood purification", "Cooking", "Juice", "Traditional medicine"],
    characteristics: ["Climbing vine", "Warty green fruit", "Extremely bitter", "Yellow flowers"],
    image: "https://images.unsplash.com/photo-1594282486756-576bf8f08608?w=400&h=300&fit=crop"
  },
  {
    id: "45",
    englishName: "Drumstick Tree",
    botanicalName: "Moringa oleifera",
    tamilName: "முருங்கைக்காய் (Murungaikkai)",
    category: "trees",
    description: "Miracle tree with nutrient-rich pods used extensively in South Indian cooking.",
    fullDescription: "Drumstick pods are a staple in South Indian cuisine, especially in sambar. The long, slender pods have a unique taste and are packed with nutrients. The tree grows quickly and is drought-resistant, making it valuable for food security.",
    habitat: "Native to India, thrives in tropical and subtropical dry climates.",
    uses: ["Cooking vegetable", "Nutritional supplement", "Water purification", "Oil production", "Animal feed"],
    characteristics: ["Fast growing", "Drooping branches", "Long green pods", "Height: up to 12 meters"],
    image: "https://images.unsplash.com/photo-1605637297601-3ee67a0cdc3d?w=400&h=300&fit=crop"
  },
  {
    id: "46",
    englishName: "Snake Plant",
    botanicalName: "Sansevieria trifasciata",
    tamilName: "மார்ப்பு மூலிகை (Marppu Mooligai)",
    category: "leaves",
    description: "Hardy indoor plant known for air purification and low maintenance needs.",
    fullDescription: "Snake Plant, also called Mother-in-law's Tongue, is one of the best air-purifying plants. It releases oxygen at night, making it ideal for bedrooms. The plant is extremely hardy and can survive neglect, low light, and irregular watering.",
    habitat: "Native to West Africa, thrives indoors in various conditions.",
    uses: ["Air purification", "Indoor decoration", "Feng Shui", "Fiber production", "Traditional medicine"],
    characteristics: ["Sword-shaped leaves", "Green with yellow edges", "Upright growth", "Height: 30-120 cm"],
    image: "https://images.unsplash.com/photo-1593482892290-f54927ae1bb6?w=400&h=300&fit=crop"
  },
  {
    id: "47",
    englishName: "Indian Basil",
    botanicalName: "Ocimum basilicum",
    tamilName: "திருநீற்றுப்பச்சை (Thiruneetru Pachai)",
    category: "herbs",
    description: "Aromatic culinary herb used in Italian and Asian cuisines worldwide.",
    fullDescription: "Sweet Basil, while different from Holy Basil, is also cultivated in India. It's the basil used in Italian cooking for pesto and caprese. The herb has antibacterial properties and aids digestion. It's easy to grow and makes an excellent kitchen garden plant.",
    habitat: "Native to tropical Asia, cultivated worldwide in warm climates.",
    uses: ["Cooking", "Pesto", "Garnish", "Herbal tea", "Traditional medicine"],
    characteristics: ["Aromatic leaves", "White flowers", "Square stems", "Height: 30-60 cm"],
    image: "https://images.unsplash.com/photo-1618164436241-4473940d1f5c?w=400&h=300&fit=crop"
  },
  {
    id: "48",
    englishName: "Flame of the Forest",
    botanicalName: "Butea monosperma",
    tamilName: "புரசு (Purasu)",
    category: "trees",
    description: "Stunning tree with brilliant orange-red flowers that carpet the forest floor.",
    fullDescription: "Flame of the Forest creates a spectacular display when it blooms, covering the tree with bright orange-red flowers. The flowers yield a natural dye used during Holi festival. The tree has numerous medicinal uses in Ayurveda.",
    habitat: "Native to South and Southeast Asia, grows in dry deciduous forests.",
    uses: ["Natural dye", "Traditional medicine", "Lac cultivation", "Fodder", "Timber"],
    characteristics: ["Crooked trunk", "Trifoliate leaves", "Orange-red flowers", "Height: 12-15 meters"],
    image: "https://images.unsplash.com/photo-1490750967868-88aa4486c946?w=400&h=300&fit=crop"
  },
  {
    id: "49",
    englishName: "Peepal Tree",
    botanicalName: "Ficus religiosa",
    tamilName: "அரசமரம் (Arasamaram)",
    category: "trees",
    description: "Sacred fig tree under which Buddha attained enlightenment, revered across religions.",
    fullDescription: "The Peepal tree is sacred to Hindus, Buddhists, and Jains. It's believed that Buddha attained enlightenment under this tree. The tree releases oxygen round the clock and is known for its heart-shaped leaves. It's planted near temples and villages.",
    habitat: "Native to Indian subcontinent, grows in tropical and subtropical climates.",
    uses: ["Religious significance", "Oxygen production", "Traditional medicine", "Shade", "Fodder"],
    characteristics: ["Heart-shaped leaves", "Aerial roots", "Sacred status", "Height: up to 30 meters"],
    image: "https://images.unsplash.com/photo-1502082553048-f009c37129b9?w=400&h=300&fit=crop"
  },
  {
    id: "50",
    englishName: "Indian Borage",
    botanicalName: "Plectranthus amboinicus",
    tamilName: "கற்பூரவல்லி (Karpooravalli)",
    category: "medicinal",
    description: "Succulent herb with oregano-like flavor used for respiratory ailments.",
    fullDescription: "Indian Borage, known as Karpooravalli, is a succulent herb with thick, fleshy leaves that have a strong oregano-like aroma. It's highly effective for treating coughs, colds, and respiratory infections. The leaves can be eaten raw or made into juice.",
    habitat: "Native to Africa and India, grows well in tropical climates.",
    uses: ["Cough remedy", "Cold relief", "Cooking", "Digestive aid", "Skin infections"],
    characteristics: ["Thick succulent leaves", "Oregano scent", "Velvety texture", "Height: 30-90 cm"],
    image: "https://images.unsplash.com/photo-1509223197845-458d87a3f2a5?w=400&h=300&fit=crop"
  }
]

export const categories = [
  { id: "all", name: "All Species", icon: "🌿" },
  { id: "leaves", name: "Leaves", icon: "🍃" },
  { id: "flowers", name: "Flowers", icon: "🌸" },
  { id: "herbs", name: "Herbs", icon: "🌱" },
  { id: "trees", name: "Trees", icon: "🌳" },
  { id: "shrubs", name: "Shrubs", icon: "🪴" },
  { id: "climbers", name: "Climbers", icon: "🌿" },
  { id: "medicinal", name: "Medicinal", icon: "💊" },
]
